name: 'Mkdir over SSH'
description: 'Connects to a server via SSH and creates a directory-tree, if it not exists already.'
inputs:
  key-name:
    description: 'Name of the file the private key is temporarily saved in. Defaults to `identity`.'
    required: true
    default: 'identity'
  port:
    description: 'The SSH port to use. Defaults to `22`.'
    required: true
    default: '22'
  dir:
    description: 'The directory that should be created on the remote machine using `mkdir -p`.'
    required: true
  user:
    description: 'The SSH user that will be used to connect to the host.'
    required: true
  host:
    description: 'The SSH-server (host) to connect to.'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Use SSH - mkdir
      shell: bash
      run: ssh -i .ssh/${{ inputs.key-name }} -p ${{ inputs.port }} -o StrictHostKeyChecking=no ${{ inputs.user }}@${{ inputs.host }} "mkdir -p ${{ inputs.dir }}"